version: "3.9"

services:
  shopsmart-gateway:
    build: .
    container_name: shopsmart-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_CONFIG_ADDITIONAL_LOCATION=/app/config/
    volumes:
      - ./src/main/resources/application.yml:/app/config/application.yml:ro
    networks:
      - shopsmart-net
    restart: unless-stopped

networks:
  shopsmart-net:
    external: true
